WhiteNet/force-app/main/default/objects/Anomaly__c/Anomaly__c.object-meta.xml
<CustomObject>
    <label>Anomaly</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Anomaly Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Anomalies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WhiteNet/force-app/main/default/objects/Anomaly__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Anomalies</relationshipLabel>
    <relationshipName>Anomalies</relationshipName>
    <type>Lookup</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Anomaly__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Anomaly__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Temperature Anomaly</fullName>
            </value>
            <value>
                <fullName>Pressure Anomaly</fullName>
            </value>
            <value>
                <fullName>Humidity Anomaly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

WhiteNet/force-app/main/default/objects/Anomaly__c/fields/Weather__c.field-meta.xml
<CustomField>
    <fullName>Weather__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Weather</label>
    <referenceTo>Weather__c</referenceTo>
    <relationshipLabel>Anomalies</relationshipLabel>
    <relationshipName>Anomalies</relationshipName>
    <type>Lookup</type>
</CustomField>

WhiteNet/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Empty/force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0}</displayFormat>
        <label>Weather Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WhiteNet/force-app/main/default/objects/Weather__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Weather</relationshipLabel>
    <relationshipName>Weather</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Empty/force-app/main/default/classes/WeatherTriggerHandler.cls
public with sharing class WeatherTriggerHandler {

    public static void handleBeforeInsert(List<Weather__c> newList){}

    public static void handleAfterInsert(List<Weather__c> newList){
        //Code here 
        //Use AnomalyDetector to detect an anomaly
        //Use SOQL to get City record information
        //insert Anomalies
        //update City
    AnomalyDetector detector = new AnomalyDetector();
    for (Weather__c weather : newList)
    {
        List<Anomaly__c> anomaly_list = detector.detectAnomaly(weather);
        List<City__c> sity_list = [
            SELECT Id
                , Name
            FROM City__c
            WHERE Id =: weather.City__c];
        City__c city_info = sity_list[0];
        for (Anomaly__c anomaly : anomaly_list)
        {
           Anomaly__c newAnomaly =  new Anomaly__c(
                Type__c = anomaly.Type__c
               , City_Name__c = city_info.Name 
               , City__c = city_info.Id 
               , Weather__c = weather.Id);
           insert(newAnomaly);
        }
    }
}

    public static void handleBeforeUpdate(List<Weather__c> newList, List<Weather__c> oldList){}

    public static void handleAfterUpdate(List<Weather__c> newList, List<Weather__c> oldList){}

    public static void handleBeforeDelete(List<Weather__c> oldList){}

    public static void handleAfterDelete(List<Weather__c> oldList){}
}