WhiteNet/force-app/main/default/objects/Anomaly__c/Anomaly__c.object-meta.xml
<CustomObject>
    <label>Anomaly</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Anomaly Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Anomalies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WhiteNet/force-app/main/default/objects/Anomaly__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Anomalies</relationshipLabel>
    <relationshipName>Anomalies</relationshipName>
    <type>Lookup</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Anomaly__c/fields/City_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Name__c</fullName>
    <label>City Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Anomaly__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Temperature Anomaly</fullName>
            </value>
            <value>
                <fullName>Pressure Anomaly</fullName>
            </value>
            <value>
                <fullName>Humidity Anomaly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

WhiteNet/force-app/main/default/objects/Anomaly__c/fields/Weather__c.field-meta.xml
<CustomField>
    <fullName>Weather__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Weather</label>
    <referenceTo>Weather__c</referenceTo>
    <relationshipLabel>Anomalies</relationshipLabel>
    <relationshipName>Anomalies</relationshipName>
    <type>Lookup</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Anomaly_Range_Configuration__c/Anomaly_Range_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Anomaly Range Configuration</label>
</CustomObject>

WhiteNet/force-app/main/default/objects/Anomaly_Range_Configuration__c/fields/Max_Humidity__c.field-meta.xml
<CustomField>
    <fullName>Max_Humidity__c</fullName>
    <label>Max Humidity</label>
    <precision>10</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Anomaly_Range_Configuration__c/fields/Max_Pressure__c.field-meta.xml
<CustomField>
    <fullName>Max_Pressure__c</fullName>
    <label>Max Pressure</label>
    <precision>10</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Anomaly_Range_Configuration__c/fields/Max_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Max_Temperature__c</fullName>
    <label>Max Temperature</label>
    <precision>10</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Anomaly_Range_Configuration__c/fields/Min_Humidity__c.field-meta.xml
<CustomField>
    <fullName>Min_Humidity__c</fullName>
    <label>Min Humidity</label>
    <precision>10</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Anomaly_Range_Configuration__c/fields/Min_Pressure__c.field-meta.xml
<CustomField>
    <fullName>Min_Pressure__c</fullName>
    <label>Min Pressure</label>
    <precision>10</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Anomaly_Range_Configuration__c/fields/Min_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Min_Temperature__c</fullName>
    <label>Min Temperature</label>
    <precision>10</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

WhiteNet/force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WhiteNet/force-app/main/default/objects/Weather__c/Weather__c.object-meta.xml
<CustomObject>
    <label>Weather</label>
    <nameField>
        <displayFormat>W-{0}</displayFormat>
        <label>Weather Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WhiteNet/force-app/main/default/objects/Weather__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Weather</relationshipLabel>
    <relationshipName>Weather</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Weather__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <label>Humidity</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Weather__c/fields/Maximum_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Temperature__c</fullName>
    <label>Maximum Temperature</label>
    <precision>8</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Weather__c/fields/Minimal_Temperature__c.field-meta.xml
<CustomField>
    <fullName>Minimal_Temperature__c</fullName>
    <label>Minimal Temperature</label>
    <precision>8</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

WhiteNet/force-app/main/default/objects/Weather__c/fields/Pressure__c.field-meta.xml
<CustomField>
    <fullName>Pressure__c</fullName>
    <label>Pressure</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WhiteNet/force-app/main/default/classes/AnomalyDetector.cls
public with sharing class AnomalyDetector {

    public Anomaly_Range_Configuration__c anomalyRandeSetting;

    public AnomalyDetector() {
        this.anomalyRandeSetting = Anomaly_Range_Configuration__c.getOrgDefaults();
    }

    public List<Anomaly__c> detectAnomaly(Weather__c weather, City__c city_info){
        List<Anomaly__c> anomaliesToSave = new List<Anomaly__c>();
     if (anomalyRandeSetting.Max_Humidity__c<=weather.Humidity__c || anomalyRandeSetting.Min_Humidity__c>=weather.Humidity__c){
         anomaliesToSave.add(new Anomaly__c(
            Type__c = 'Humidity Anomaly'
            , Weather__c = weather.Humidity__c
            , City__c = weather.City__c
            , City_Name__c= city_info.Name
         ));  
     }
     if (anomalyRandeSetting.Max_Pressure__c<=weather.Pressure__c || anomalyRandeSetting.Min_Pressure__c>=weather.Pressure__c){
        anomaliesToSave.add(new Anomaly__c(
            Type__c = 'Pressure Anomaly'
            , Weather__c = weather.Pressure__c
            , City__c = weather.City__c
            , City_Name__c= city_info.Name
        ));  
    }
     if (anomalyRandeSetting.Max_Temperature__c<=weather.Maximum_Temperature__c){
        anomaliesToSave.add(new Anomaly__c(
            Type__c = 'Temperature Anomaly'
            , Weather__c = weather.Maximum_Temperature__c
            , City__c = weather.City__c
            , City_Name__c= city_info.Name
        )); 
    }
     if (anomalyRandeSetting.Min_Temperature__c>=weather.Minimal_Temperature__c){
        anomaliesToSave.add(new Anomaly__c(
            Type__c = 'Temperature Anomaly'
            , Weather__c = weather.Minimal_Temperature__c
            , City__c = weather.City__c
            , City_Name__c= city_info.Name
        )); 
    }  
    return anomaliesToSave;
    }
}